## This document describes how to reproduce the figures of the article.
## The working directory (as set by 'setwd') must be the root folder 'smcsamplers'

#### Logistic regression on the covtype data set ####

## first obtain data from
## https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary.html
## https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary/covtype.libsvm.binary.scale.bz2
## unzip to obtain file covtype.libsvm.binary.scale
## and execute logistic/covtype_process.R
## you might have to change the path "~/Downloads/"
source("inst/logistic/covtype_process.R")
# The above creates covtype.processed.RData in experiments/logistic/
# where it is needed for the scripts below to run

# To generate Figures 2(a) and 2(b)
source("inst/logistic/covtype_priormerging.R") # creates covtype.merging.RData
source("inst/logistic/covtype_priormerging_plots.R") # creates plots

# To generate Figures 2(c) and 2(d)
source("inst/logistic/covtype_predperf.R") # creates covtype.predperf.RData
source("inst/logistic/covtype_predperf_plots.R") # creates plots

## For "different paths" in Supplementary Material S5
source("inst/logistic/covtype_smc_tempering.R") # creates covtype.smctempering.RData
source("inst/logistic/covtype_smc_partial.R") # creates covtype.smcpartial.RData
## the code requires 'pgdraw'
if (!require("pgdraw")) install.packages("pgdraw")
source("inst/logistic/covtype_smc_pgg.R") # creates covtype.smcpgg.RData

## The plots of Figures S3 in Section S5 "Logistic regression: different paths"
source("inst/logistic/covtype_pathcomparison_plot.R")

## For "Partial posterior averaged over orderings" in Supplementary Material S6
source("inst/logistic/covtype_averagepartial.R") # creates covtype.partial.average.RData
source("inst/logistic/covtype_averagepartial_plots.R")

## For Laplace approximations in Supplementary Material S7
## the code requires numDeriv
if (!require("numDeriv")) install.packages("numDeriv")
source("inst/logistic/covtype_laplace.R") # creates covtype.laplace.n*.RData
source("inst/logistic/covtype_laplace_plots.R") # creates plots

#### SIR model on the boarding school data set ####
## the code requires 'outbreaks', 'rstan'
if (!require("outbreaks")) install.packages("outbreaks")
if (!require("rstan")) install.packages("rstan")
## run
source("inst/sirmodel/boardingschool-smc-partialposteriors.R") # creates boardingschool-smc-partial.RData
source("inst/sirmodel/boardingschool-marginal.R") # creates boardingschool-smc-marginal.RData
## the four plots of Figure 3 are created with
source("inst/sirmodel/boardingschool-plots.R")

## For the results with multivariate Normals in the Supplementary Materials
source("inst/mvnorm/mvnorm_scalingdimension_run.R")
source("inst/mvnorm/mvnorm_moreintermediatesteps_run.R")
source("inst/mvnorm/mvnorm_plots.R")
## The first two scripts generate RData files, the last one generates the plots.

## A previous version of the arXiv draft had some genealogical trees, generated by the script trees/treeplots.R
## It requires tidyverse, igraph, ggraph.
source("inst/trees/treeplots.R")

