# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
coxprocess_loglikelihood <- function(x, counts, area) {
    .Call('_temperingsmc_coxprocess_loglikelihood', PACKAGE = 'temperingsmc', x, counts, area)
}

#' @export
eigenMapMatMult <- function(A, B) {
    .Call('_temperingsmc_eigenMapMatMult', PACKAGE = 'temperingsmc', A, B)
}

dmvnorm_ <- function(x, mean, covariance) {
    .Call('_temperingsmc_dmvnorm_', PACKAGE = 'temperingsmc', x, mean, covariance)
}

dmvnorm_cholesky_inverse <- function(x, mean, cholesky_inverse) {
    .Call('_temperingsmc_dmvnorm_cholesky_inverse', PACKAGE = 'temperingsmc', x, mean, cholesky_inverse)
}

grad_dmvnorm_precision <- function(x, mean, precision) {
    .Call('_temperingsmc_grad_dmvnorm_precision', PACKAGE = 'temperingsmc', x, mean, precision)
}

rmvnorm_ <- function(nsamples, mean, covariance) {
    .Call('_temperingsmc_rmvnorm_', PACKAGE = 'temperingsmc', nsamples, mean, covariance)
}

rmvnorm_cholesky_ <- function(nsamples, mean, cholesky) {
    .Call('_temperingsmc_rmvnorm_cholesky_', PACKAGE = 'temperingsmc', nsamples, mean, cholesky)
}

#' @export
dmvstudent_t_cholesky_inverse <- function(x, degree, mean, cholesky_inverse, constant, factor) {
    .Call('_temperingsmc_dmvstudent_t_cholesky_inverse', PACKAGE = 'temperingsmc', x, degree, mean, cholesky_inverse, constant, factor)
}

#' @export
grad_dmvstudent_t <- function(x, degree, mean, precision, factor) {
    .Call('_temperingsmc_grad_dmvstudent_t', PACKAGE = 'temperingsmc', x, degree, mean, precision, factor)
}

#' @export
systematic_resampling <- function(weights, ndraws, u) {
    .Call('_temperingsmc_systematic_resampling', PACKAGE = 'temperingsmc', weights, ndraws, u)
}

